spring:
  datasource:
    url: ${BOOKTRACKR_DB_URL}
    username: ${BOOKTRACKR_DB_USERNAME}
    password: ${BOOKTRACKR_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate

graphite:
  host: ${GRAPHITE_HOST}
  post: ${GRAPHITE_PORT}
  apiKey: ${GRAPHITE_API_KEY}

jwt:
  signing-secret: ${JWT_SIGNING_SECRET}
